syntax = "proto3";

package lot;

option go_package = "github.com/s-usmonalizoda25/protoAuction/gen/lot;lotv1";

service LotService {
    rpc CreateLot(CreateLotRequest) returns (CreateLotResponse);
    rpc GetLot(GetLotRequest) returns (GetLotResponse);
    rpc ListLots(ListLotsRequest) returns (ListLotsResponse);
    rpc CancelLot(CancelLotRequest) returns (CancelLotResponse);


    rpc ApproveLot(ApproveLotRequest) returns (ApproveLotResponse);
    rpc RejectLot(RejectLotRequest) returns (RejectLotResponse);


    rpc UpdateCurrentPrice(UpdateCurrentPriceRequest) returns (UpdateCurrentPriceResponse);
}

message CreateLotRequest {
    int64 seller_id = 1;
    string title = 2;
    string description = 3;
    int64 starting_price_minor = 4;
    int64 starts_at = 5;
    int64 ends_at = 6;
}

message CreateLotResponse {
    int64 lot_id = 1;
    string status = 2;
}

message GetLotRequest { int64 lot_id = 1; }

message GetLotResponse {
    int64 lot_id = 1;
    int64 seller_id = 2;
    string title = 3;
    string description = 4;
    int64 starting_price_minor = 5;
    int64 current_price_minor = 6;
    string status = 7;
    bool has_bids = 8;
    int64 starts_at = 9;
    int64 ends_at = 10;
}

message ListLotsRequest {
    string status = 1;
    int32 page = 2;
    int32 limit = 3;
}

message ListLotsResponse {
    repeated GetLotResponse lots = 1;
    int32 total = 2;
}

message CancelLotRequest { int64 lot_id = 1; int64 requester_id = 2; }
message CancelLotResponse { bool success = 1; }

message ApproveLotRequest { int64 lot_id = 1; }
message ApproveLotResponse { bool success = 1; }

message RejectLotRequest { int64 lot_id = 1; string reason = 2; }
message RejectLotResponse { bool success = 1; }

message UpdateCurrentPriceRequest {
    int64 lot_id = 1;
    int64 current_price_minor = 2;
    bool has_bids = 3;
}
message UpdateCurrentPriceResponse { bool success = 1; }